openapi: '3.0.1'
info:
  $ref: "./api/info/index.yaml"
servers:
- url: "http://localhost:8080/api/v1"
- url: "https://localhost:8080/api/v1"

paths:
  $ref: ./api/paths/index.yaml

components:
  $ref: ./api/components/index.yaml
